#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - unzip
  - inotify-tools

write_files:
  - content: ${filebase64("${twitter-credentials}")}
    encoding: b64
    owner: root:root
    path: /home/ubuntu/credentials/twitter/application.conf
    permissions: '0444'
  - content: ${filebase64("${github-credentials}")}
    encoding: b64
    owner: root:root
    path: /root/.ssh/id_rsa
    permissions: '0400'
  

runcmd:
  - 'sudo chmod 666 /var/run/docker.sock'
  - 'mv /tmp/resources /home/ubuntu/'
  - 'cd /home/ubuntu'
  - 'chmod 0666 /root/.ssh/known_hosts'
  - 'mv resources/known_hosts /root/.ssh/known_hosts'
  - 'mv resources/*.sh .'
  - 'curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip'
  - 'unzip awscliv2.zip'
  - './aws/install'
  - 'rm awscliv2.zip'
  - 'eval "$(ssh-agent -s)"'
  - 'sleep 5'
  - 'ssh-add /root/.ssh/id_rsa'
  - 'sleep 2'
  - 'git clone git@github.com:lamastex/mep.git'
  - 'mv credentials/twitter/application.conf mep/sc/tw/src/main/resources/application.conf'
  - 'rm mep/sc/tw/build_Sp2x_Sc3_13.sbt'
  - 'mv mep/sc/tw twitter-scala'
  - 'rm -rf mep'
  - 'mv resources twitter-config'
  - 'rm -rf ${config-repo}'
  - 'mkdir files-being-written-to'
  - 'mkdir files-complete'
  - 'mkdir files-to-s3'
  - 'sudo chown -R ubuntu /home/ubuntu'
  - 'chmod +x *.sh'
  - 'runuser -u ubuntu -- ./monitor-directory.sh &'
  - 'runuser -u ubuntu -- ./contingency-monitor.sh &'
  - './docker-run.sh &'
